language: objective-c

branches:
 only:
 - master

xcode_project: TravisTest.xcodeproj
xcode_scheme: TravisTest
osx_image: xcode7.2
xcode_sdk: iphonesimulator9.2

script:
- xcodebuild clean build test -project TravisTest.xcodeproj -scheme TravisTest