language: objective-c

branches:
 only:
 - master

xcode_workspace: TravisTest.xcworkspace
xcode_scheme: TravisTest
osx_image: xcode7.2
xcode_sdk: iphonesimulator9.2

script:
- xcodebuild clean build test -workspace TravisTest.xcworkspace -scheme TravisTest

xcode_workspace: TravisTest.xcworkspace
xcode_scheme: TravisTVTest
osx_image: xcode7.2
xcode_sdk: tvos9.0

script:
- xcodebuild clean build test -workspace TravisTest.xcworkspace -scheme TravisTVTest